# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Deploy App

on:
  push:
    branches: 
      - devel
      - stage
      - prod
  pull_request:
    branches: 
      - devel
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rdicidr-0.1.0

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"
    
    - name: Install dependencies
      run: npm ci
    
    - name: Linter (ESLint)
      run: npm run lint
    
    - name: Formatter (Prettier)
      run: npm run prettier
    
    - name: Formatter (Prettier)
      run: npm run prettier
    
    - name: Test (Jest)
      run: CI=true npm run test

    - name: Build 
      run: npm run build
