# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Validate Pull Requests
on:
  pull_request:
    branches: 
      - devel
      - stage
      - prod
  
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    
    - name: Validate Pull Request
      run: |
        if [[ "${{ github.base_ref }}" == "devel"]]; then
          if [[ ! "${{ github.head_ref }}" =~ ^(feature|bugfix) ]]; then
            echo "Only allow merges into the devel branch from branches feature/bugfix."
            exit 1
          fi
        elif [[ "${{ github.base_ref }}" == "stage"]]; then
          if [[ ! "${{ github.head_ref }}" != "devel" ]]; then
            echo "Only allow merges into the stage branch from the devel branch"
            exit 1
          fi
        elif [[ "${{ github.base_ref }}" == "prod"]]; then
          if [[ ! "${{ github.head_ref }}" != "stage" ]]; then
            echo "Only allow merges into the prod branch from the stage branch"
            exit 1
          fi
        fi